### ISSUE TITLE
Start-up notebook

### ISSUE THREAD

**Issue by dhavide** [ScienceCore/scipy-2024-climaterisk#7]
@jnywong or @jmunroe , I notice that when I start my instance, the Jupyterlab session automatically loads the notebook `00_Introduction_Setup/02_Introduction_to_Open_Science.ipynb` from the `scipy-2024-climaterisk` repository.

Could you modify the set up so that the notebook `00_Introduction_Setup/01_Initial_Setup.ipynb` is loaded instead?

**Comment by jmunroe** [comment]
Yes. I'll make that change.

**Comment by jmunroe** [comment]
Modified by https://github.com/2i2c-org/infrastructure/pull/4372
